### ISSUE TITLE
Is container property optional?

### ISSUE THREAD

**Issue by itsheng** [webix-hub/angular2-demo#2]
I have followed the example and created my own component. It seems if I ignore the container property, everything still works fine? The webix ui will render the component correctly.

constructor(private router: Router, root: ElementRef) {
    this.ui = <webix.ui.menu>webix.ui({
      container: root.nativeElement,

Similar to above code, I actually didn't add container parameter. How could webix figure the right place to render itself? What's the magic here?
Thanks!

**Comment by mkozhukh** [comment]
If container is not defined, component will be rendered inside of document.body
So, it is optional only for top level component

**Comment by itsheng** [comment]
Thanks for the answer!
