### ISSUE TITLE
using angular cli

### ISSUE THREAD

**Issue by cesarcastmore** [webix-hub/angular2-demo#3]
#1 I am trying to develop web.ui.datatable using angular cli. When I am running my serve. I have the error " Cannot find namespace 'webix'". I have the following code 

------------------------------------------------------------------------------------------------

app.component.ts

import { Component, ElementRef, OnDestroy, OnInit } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})

export class AppComponent implements OnDestroy, OnInit {
  private ui : webix.ui.datatable;
  
   ngOnInit(){
      this.ui.resize();
    }

   ngOnDestroy(){
      this.ui.destructor();
    }
 }
------------------------------------------------------------------------------------

angular-cli.json
{
  "project": {
    "version": "1.0.0-beta.28.3",
    "name": "app-tegik"
  },
  "apps": [
    {
      "root": "src",
      "outDir": "dist",
      "assets": [
        "assets",
        "favicon.ico"
      ],
      "index": "index.html",
      "main": "main.ts",
      "polyfills": "polyfills.ts",
      "test": "test.ts",
      "tsconfig": "tsconfig.json",
      "prefix": "app",
      "styles": [
        "styles.css", 
        "../node_modules/webix/webix.css", 
        "../node_modules/bootstrap/dist/css/bootstrap.css"
      ],
      "scripts": [
        "../node_modules/webix/webix.js"],
      "environments": {
        "source": "environments/environment.ts",
        "dev": "environments/environment.ts",
        "prod": "environments/environment.prod.ts"
      }
    }
  ],
  "e2e": {
    "protractor": {
      "config": "./protractor.conf.js"
    }
  },
  "lint": [
    {
      "files": "src/**/*.ts",
      "project": "src/tsconfig.json"
    },
    {
      "files": "e2e/**/*.ts",
      "project": "e2e/tsconfig.json"
    }
  ],
  "test": {
    "karma": {
      "config": "./karma.conf.js"
    }
  },
  "defaults": {
    "styleExt": "css",
    "prefixInterfaces": false,
    "inline": {
      "style": false,
      "template": false
    },
    "spec": {
      "class": false,
      "component": true,
      "directive": true,
      "module": false,
      "pipe": true,
      "service": true
    }
  }
}

**Comment by artemkosenko** [comment]
I'm having the same issue.
Always see the following error "Cannot find namespace 'webix'."
I'm using angular cli
Typings are installed (npm install @types/webix --save)

**Comment by mkozhukh** [comment]
You need to add webix into src/tsconfig.app.json

```json

{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "outDir": "../out-tsc/app",
    "module": "es2015",
    "baseUrl": "",
    "types": [ "webix" ]
  },
```
https://github.com/webix-hub/angular2-demo/blob/angular-cli/src/tsconfig.app.json
